name: development
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  macos:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test --enable-test-discovery --sanitize=thread
    - name: Generate documentation
      uses: steven0351/publish-jazzy-docs@v1
      with:
        personal_access_token: ${{ secrets.ACCESS_TOKEN }}
  ubuntu-bionic:
    runs-on: ubuntu-latest
    container:
      image: swift:5.1-bionic
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test --enable-test-discovery --sanitize=thread
  ubuntu-xenial:
    runs-on: ubuntu-latest
    container:
      image: swift:5.1-xenial
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test --enable-test-discovery --sanitize=thread
